### ISSUE TITLE
Instructions for docker

### ISSUE THREAD

**Issue by nimbo78** [nonoo/yt-dlp-telegram-bot#15]
Could you please add instructions on how to run the script correctly in docker and docker-compose.yml?

Seems like I'm missing something when trying to run script with docker containers...

**Comment by kegfru** [comment]
Example docker-compose file
```
services:
  yt-dlp-tg-bot:
    build: .
    restart: always
    environment:
      # https://my.telegram.org/apps
      API_ID: 12345678
      API_HASH: 476c7a3_example_hash_d1f9edc0a74
      BOT_TOKEN: "1234567890:ABCDEFGab_UG0_example_token_yMtSVBe"
      ALLOWED_USERIDS: "123456789,987654321"
      ADMIN_USERIDS: "123456789"
      ALLOWED_GROUPIDS: ""
      MAX_SIZE: 512MB
```
